name: Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: chrislennon/action-drone@v1
        with:
          version: '0.8.1'
      - run: drone info
        env:
          DRONE_SERVER: https://cloud.drone.io/cbailoni/DevOps-Avionics
          DRONE_TOKEN: u4IACZdDv8cTLGIpI57Ot35sFm1RjGIN
